# Generated by Django 3.2.7 on 2021-10-01 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('name', models.CharField(max_length=50, verbose_name='Название машины')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет машины')),
                ('motor', models.CharField(max_length=50, verbose_name='Объем двигателя')),
                ('drive_unit', models.CharField(max_length=50, verbose_name='Привод машины')),
                ('fuel_type', models.CharField(max_length=50, verbose_name='Тип топлива')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('car_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
